---
abstract: 'test your dist with every testing plugin conceivable'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Moose::Autobox: '0'
  Path::Tiny: '0'
  Test::DZil: '0'
  Test::More: '0.88'
  autodie: '0'
  perl: '5.006'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-TestingMania
no_index:
  directory:
    - corpus
    - inc
    - examples
requires:
  Dist::Zilla::Plugin::MetaTests: '0'
  Dist::Zilla::Plugin::MojibakeTests: '0.2'
  Dist::Zilla::Plugin::PodCoverageTests: '0'
  Dist::Zilla::Plugin::PodSyntaxTests: '0'
  Dist::Zilla::Plugin::Test::CPAN::Changes: '0.005'
  Dist::Zilla::Plugin::Test::CPAN::Meta::JSON: '0.003'
  Dist::Zilla::Plugin::Test::Compile: '2.033'
  Dist::Zilla::Plugin::Test::DistManifest: '2.000001'
  Dist::Zilla::Plugin::Test::EOL: '0'
  Dist::Zilla::Plugin::Test::Kwalitee: '2.020000'
  Dist::Zilla::Plugin::Test::MinimumVersion: '2.000001'
  Dist::Zilla::Plugin::Test::NoTabs: '0.02'
  Dist::Zilla::Plugin::Test::Perl::Critic: '2.112410'
  Dist::Zilla::Plugin::Test::Pod::LinkCheck: '1.001'
  Dist::Zilla::Plugin::Test::Portability: '2.000001'
  Dist::Zilla::Plugin::Test::Synopsis: '2.000001'
  Dist::Zilla::Plugin::Test::UnusedVars: '2.000001'
  Dist::Zilla::Plugin::Test::Version: '0.001002'
  Dist::Zilla::Role::PluginBundle::Easy: '0'
  JSON::PP: '2.27103'
  List::MoreUtils: '0'
  Moose: '0'
  Pod::Coverage::TrustPod: '0'
  Test::CPAN::Meta: '0'
  Test::Perl::Critic: '0'
  Test::Version: '0.07'
  namespace::autoclean: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/doherty/Dist-Zilla-PluginBundle-TestingMania/issues
  homepage: http://metacpan.org/release/Dist-Zilla-PluginBundle-TestingMania/
  repository: git://github.com/doherty/Dist-Zilla-PluginBundle-TestingMania.git
version: '0.23'
