---
abstract: 'A bundle to test your dist with every testing plugin conceivable'
author:
  - 'Mike Doherty <doherty@cs.dal.ca>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-TestingMania
requires:
  Dist::Zilla::Plugin::ApacheTest: 0
  Dist::Zilla::Plugin::CheckChangesTests: 0
  Dist::Zilla::Plugin::CompileTests: 0
  Dist::Zilla::Plugin::ConsistentVersionTest: 0
  Dist::Zilla::Plugin::CriticTests: 0
  Dist::Zilla::Plugin::DistManifestTests: 0
  Dist::Zilla::Plugin::EOLTests: 0
  Dist::Zilla::Plugin::HasVersionTests: 0
  Dist::Zilla::Plugin::KwaliteeTests: 0
  Dist::Zilla::Plugin::MetaTests: 0
  Dist::Zilla::Plugin::MinimumVersionTests: 0
  Dist::Zilla::Plugin::NoTabsTests: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSpellingTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PortabilityTests: 0
  Dist::Zilla::Plugin::ProgCriticTests: 0
  Dist::Zilla::Plugin::SynopsisTests: 0
  Dist::Zilla::Plugin::UnusedVarsTests: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  perl: 5.0100
resources:
  bugtracker: http://github.com/doherty/Dist-Zilla-PluginBundle-TestingMania/issues
  repository: http://github.com/doherty/Dist-Zilla-PluginBundle-TestingMania
version: 0.001
