---
abstract: 'test your dist with every testing plugin conceivable'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Path: 0
  File::Temp: 0
  Moose::Autobox: 0
  Test::DZil: 0
  Test::More: 0.88
  autodie: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-TestingMania
requires:
  Dist::Zilla::Plugin::CompileTests: 0
  Dist::Zilla::Plugin::ConsistentVersionTest: 0
  Dist::Zilla::Plugin::CriticTests: 1.102280
  Dist::Zilla::Plugin::DistManifestTests: 0
  Dist::Zilla::Plugin::EOLTests: 0.02
  Dist::Zilla::Plugin::HasVersionTests: 0
  Dist::Zilla::Plugin::KwaliteeTests: 0
  Dist::Zilla::Plugin::MetaTests: 0
  Dist::Zilla::Plugin::MinimumVersionTests: 0
  Dist::Zilla::Plugin::NoTabsTests: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PortabilityTests: 0
  Dist::Zilla::Plugin::SynopsisTests: 0
  Dist::Zilla::Plugin::Test::CPAN::Changes: 0
  Dist::Zilla::Plugin::Test::CPAN::Meta::JSON: 0.003
  Dist::Zilla::Plugin::Test::Pod::LinkCheck: 0
  Dist::Zilla::Plugin::UnusedVarsTests: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  Pod::Coverage::TrustPod: 0
  Test::CPAN::Meta: 0
  Test::Perl::Critic: 0
  perl: 5.010001
resources:
  bugtracker: https://github.com/doherty/Dist-Zilla-PluginBundle-TestingMania/issues
  homepage: http://p3rl.org/Dist::Zilla::PluginBundle::TestingMania
  repository: git://github.com/doherty/Dist-Zilla-PluginBundle-TestingMania.git
version: 0.010
