---
abstract: 'test your dist with every testing plugin conceivable'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Path: 0
  File::Temp: 0
  Moose::Autobox: 0.11
  Test::DZil: 4.200007
  Test::More: 0.88
  autodie: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-TestingMania
requires:
  Dist::Zilla::Plugin::CompileTests: 1.110930
  Dist::Zilla::Plugin::CriticTests: 1.102280
  Dist::Zilla::Plugin::DistManifestTests: 1.101420
  Dist::Zilla::Plugin::EOLTests: 0.02
  Dist::Zilla::Plugin::KwaliteeTests: 1.101420
  Dist::Zilla::Plugin::MetaTests: 4.200007
  Dist::Zilla::Plugin::MinimumVersionTests: 1.101421
  Dist::Zilla::Plugin::MojibakeTests: 0.3
  Dist::Zilla::Plugin::NoTabsTests: 0.01
  Dist::Zilla::Plugin::PodCoverageTests: 4.200007
  Dist::Zilla::Plugin::PodSyntaxTests: 4.200007
  Dist::Zilla::Plugin::PortabilityTests: 1.101420
  Dist::Zilla::Plugin::SynopsisTests: 1.101420
  Dist::Zilla::Plugin::Test::CPAN::Changes: 0.004
  Dist::Zilla::Plugin::Test::CPAN::Meta::JSON: 0.003
  Dist::Zilla::Plugin::Test::Pod::LinkCheck: 1.000
  Dist::Zilla::Plugin::Test::Version: 0.001002
  Dist::Zilla::Plugin::UnusedVarsTests: 1.100860
  Dist::Zilla::Role::PluginBundle::Easy: 4.200007
  Moose: 2.0007
  Pod::Coverage::TrustPod: 0.100000
  Test::CPAN::Meta: 0.18
  Test::Perl::Critic: 1.02
  Test::Version: 0.07
  perl: 5.010001
resources:
  bugtracker: https://github.com/doherty/Dist-Zilla-PluginBundle-TestingMania/issues
  homepage: http://p3rl.org/Dist::Zilla::PluginBundle::TestingMania
  repository: git://github.com/doherty/Dist-Zilla-PluginBundle-TestingMania.git
version: 0.012
